enum UserActionTypes {
  SET_USER = "SET_USER",
  SEARCH_USERS = "SEARCH_USERS",
  GET_USERS_START = "GET_USERS_START",
  GET_USERS_SUCCESS = "GET_USERS_SUCCESS",
  GET_USERS_FAILURE = "GET_USERS_FAILURE",
}

export default UserActionTypes;
